[package]
name = "dtn-hdy-utils"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
hardy-bpa = { path = "../hardy/bpa", features = ["serde", "tokio"] }
hardy-proto = { path = "../hardy/proto" }
hardy-bpv7 = { path = "../hardy/bpv7", features = ["std", "serde", "rfc9173"] }
tokio = { version = "1.52.3", features = ["full"] }
anyhow = "1.0.102"
time = "0.3.49"
bytes = "1.11.1"
rusqlite = { version = "0.40", features = ["array", "bundled", "time"] }
sqlx = { version = "0.9", default-features = false, features = ["postgres", "runtime-tokio", "macros", "time"] }
config = { version = "0.15", features = ["yaml", "toml", "json"] }
sha1 = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
directories = "5"
tempfile = "3"
hex = "0.4"
base64 = "0.22"
toml = "0.8"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
tokio-rustls = "0.26"
rustls-pki-types = "1"
webpki-roots = "1.0"

regex = "1"
sha2 = "0.10"
hardy-cbor = { path = "../hardy/cbor" }

rustls = "0.23"

[patch.crates-io]
sqlx-sqlite = { path = "../hardy/patches/sqlx-sqlite" }

